spring.application.name=fitassist-backend
server.port=8080

# H2 Veritabanını artık bellekte (mem) değil, bilgisayarında bir dosyada (file) tutuyoruz
# Bu sayede projeyi kapatsan bile verilerin (su, beslenme, antrenman) silinmeyecek.
# Verileri RAM yerine projenin içindeki "data" klasörüne kalıcı olarak kaydeder
spring.datasource.url=jdbc:h2:file:./data/fitassistdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Veritabanı tablolarını kodlara göre otomatik oluştur ve güncelle
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=${PORT:8080}