# ===============================
# TEMEL SUNUCU AYARLARI
# ===============================
spring.application.name=fitassist-backend
# ===============================
# POSTGRESQL VERİTABANI BAĞLANTI AYARLARI (GÜVENLİ)
# ===============================
# Şifreler GitHub'a gitmesin diye ${} ile çevre değişkenlerine bağladık.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
# ===============================
# HİBERNATE VE JPA AYARLARI
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# ===============================
# RENDER CANLI SUNUCU PORT AYARI
# ===============================
server.port=${PORT:8080}
# Spring Boot her başladığında schema.sql dosyasını okur ve çalıştırır
spring.sql.init.mode=always
