spring.application.name=fitassist-backend
server.port=8080

# H2 Veritabanını artık bellekte (mem) değil, bilgisayarında bir dosyada (file) tutuyoruz
# Bu sayede projeyi kapatsan bile verilerin (su, beslenme, antrenman) silinmeyecek.
spring.datasource.url=jdbc:h2:file:./veritabani/fitassistdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Veritabanı tablolarını kodlara göre otomatik oluştur ve güncelle
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true